### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by cybercamphackathon** [CarlosLannister/OwadeReborn#1]
Add project dependencies and basic usage example information

**Comment by CarlosLannister** [comment]
Requeriments.txt and install guide is going to be upladed soon. We are working on that right now, its going to be uploaded in a few hours.

**Comment by CarlosLannister** [comment]
You can check the WiKi for install and tutorials. https://github.com/CarlosLannister/OwadeReborn/wiki
